CI: Temporarily limit CI tests to Python 3.10+
- Remove Python 3.8 and 3.9 from test matrix in GitHub Actions
- Cause workflow run to pass and temporarily resolves "TypeError: signature() got an unexpected keyword argument 'eval_str'" error in workflow run
- Revert to initial 'test_version_command' implementation.

This is a temporary measure to allow CI pipeline to succeed while I try to resolve test framework issues with Python 3.8 and 3.9.
The package itself still supports and works with Python 3.8+.
TODO: Investigate and fix test issues with earlier Python versions.

Signed-off-by: Excel Chukwu <excel.chukwu1.0@gmail.com>